/*
 * This class file was automatically generated by ASN1bean v1.13.0 (http://www.beanit.com)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import com.beanit.asn1bean.ber.types.BerBitString;

public class ACSERequirements extends BerBitString {

    private static final long serialVersionUID = 1L;

    public ACSERequirements() {
    }

    public ACSERequirements(byte[] code) {
        super(code);
    }

    public ACSERequirements(byte[] value, int numBits) {
        super(value, numBits);
    }

    public ACSERequirements(boolean[] value) {
        super(value);
    }

}
