/*
 * This class file was automatically generated by ASN1bean v1.13.0 (http://www.beanit.com)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import com.beanit.asn1bean.ber.types.BerOctetString;

public class AEQualifierForm2 extends BerOctetString {

    private static final long serialVersionUID = 1L;

    public AEQualifierForm2() {
    }

    public AEQualifierForm2(byte[] value) {
        super(value);
    }

}
