/*
 * This class file was automatically generated by ASN1bean v1.13.0 (http://www.beanit.com)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import java.math.BigInteger;

import com.beanit.asn1bean.ber.types.BerInteger;

public class AssociateResult extends BerInteger {

    private static final long serialVersionUID = 1L;

    public AssociateResult() {
    }

    public AssociateResult(byte[] code) {
        super(code);
    }

    public AssociateResult(BigInteger value) {
        super(value);
    }

    public AssociateResult(long value) {
        super(value);
    }

}
