/*
 * This class file was automatically generated by ASN1bean v1.13.0 (http://www.beanit.com)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import com.beanit.asn1bean.ber.types.string.BerGraphicString;

public class ImplementationData extends BerGraphicString {

    private static final long serialVersionUID = 1L;

    public ImplementationData() {
    }

    public ImplementationData(byte[] value) {
        super(value);
    }

}
