/*
 * This class file was automatically generated by ASN1bean v1.13.0 (http://www.beanit.com)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;

public class MechanismName extends BerObjectIdentifier {

    private static final long serialVersionUID = 1L;

    public MechanismName() {
    }

    public MechanismName(byte[] code) {
        super(code);
    }

    public MechanismName(int[] value) {
        super(value);
    }

}
